name: docflow-pro
services:
- name: frontend
  source_dir: /frontend
  github:
    repo: heyitsharman/DocFlow
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: ${backend.DEPLOYED_URL}/api
- name: backend
  source_dir: /Backend
  github:
    repo: heyitsharman/DocFlow
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: YOUR_MONGODB_CONNECTION_STRING
  - key: JWT_SECRET
    value: YOUR_JWT_SECRET_HERE